version: '3.4'

services:
  internetmonitoring:
    image: internetmonitoring
    build:
      context: .
      dockerfile: ./Dockerfile

  postgres:
      image: postgres:14.1
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data